# Binary Classification & Vectorization - Code Examples

## Week 2 Part 2 - Hands-on Implementation

### Sections:
1. Binary Classification Setup
2. Matrix Operations & Transpose Examples  
3. Vectorization Performance Comparison
4. NumPy Broadcasting Examples
5. Neural Network Prediction Implementation

## Visual Example of Transpose

In [ ]:


%pip install numpy
import numpy as np

# Original weight vector w
w = np.array([[0.2],  # Weight for feature 1
              [0.3],  # Weight for feature 2
              [0.1]]) # Weight for feature 3

print("Original w:")
print("Shape: ",w.shape)    # (3,1) - column vector
print("w =")
print(w)

print("\nTransposed w.T:")
print("Shape:", w.T.shape)  # (1, 3) - row vector
print("w.T =")
print(w.T)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 4.0 MB/s eta 0:00:00a 0:00:01
Note: you may need to restart the kernel to use updated packages.
Original w:
Shape:  (3, 1)
w =
[[0.2]
 [0.3]
 [0.1]]

Transposed w.T:
Shape: (1, 3)
w.T =
[[0.2 0.3 0.1]]


### Why Do We Need w.T in Neural Networks?

In [3]:
# Our data setup
# Shape: (3,4) - 3 rows and 4 columns
# 3 features x 4 examples
X = np.array(
    [
        [1.0, 2.0, 3.0, 4.0],
        [0.5, 1.5, 2.5, 3.5],
        [2.0, 1.0, 3.0, 2.5],
    ]
)

# Shape: (3,1) - 3 rows and 1 column
# 3 features x 1
w = np.array(
    [
        [0.2],
        [0.3],
        [0.1]
    ]
)

print("X shape:", X.shape)  # (3,4)
print("w shape:",w.shape)   # (3,1)
print("w.T shape:",w.T.shape)   #(1,3)

X shape: (3, 4)
w shape: (3, 1)
w.T shape: (1, 3)


#### Case 1: Using w (without Transpose) - Error

In [4]:
try:
    # (3,1) x (3,4) - Incompatible
    result = np.dot(w, X)
except ValueError as e:
    print("Error: ",e)

Error:  shapes (3,1) and (3,4) not aligned: 1 (dim 1) != 3 (dim 0)


#### Case 2: Using w.T (with Transpose) - Works

In [5]:
# (1,3) x (3,4) = (1,4)
result = np.dot(w.T, X)
print("w.T x X shape: ",result.shape)
print("w.T x X=",result)

w.T x X shape:  (1, 4)
w.T x X= [[0.55 0.95 1.65 2.1 ]]


### Step-Step Matrix Multiplication

In [12]:
# Manual calculation to show what np.dot(w.T, X) computes
print("Manual calculation of w.T x X:")
print()

# Shape: (3,1) - 3 rows and 1 column
# 3 features x 1
# w = np.array(
#     [
#         [0.2],
#         [0.3],
#         [0.1]
#     ]
# )

# Shape: (1,3) - 1 row, 3 column
# w.T = [[0.2, 0.3, 0.1]]

# X Shape: (3,4) - 3 rows and 4 columns
# 3 features x 4 examples
# X = np.array(
#     [
#         [1.0, 2.0, 3.0, 4.0],
#         [0.5, 1.5, 2.5, 3.5],
#         [2.0, 1.0, 3.0, 2.5],
#     ]
# )

print("Matrix shapes:")
print(f"w.T shape: {w.T.shape}")
print(f"X shape: {X.shape}")
print(f"Result shape will be: ({w.T.shape[0]}, {X.shape[1]})")
print()

print("Number of examples to process:", X.shape[1])
print()

# For each example (column)
for example in range(X.shape[1]):
    calculation = ""
    result = 0

    print(f"Processing example {example + 1}:")
    
    # For each feature (row)
    for feature in range(X.shape[0]):
        w_val = w[feature, 0] # Weight for this feature
        x_val = X[feature, example] # Feature value for this example

        contribution = w_val * x_val
        result += contribution
        
        print(f"  Feature {feature + 1}: {w_val} × {x_val} = {contribution}")

        calculation += f"{w_val} × {x_val}"
        if feature < X.shape[0] - 1:
            calculation += " + "

    print(f"  Final: {calculation} = {result:.3f}")
    print()

# Verify with NumPy
print("Verification with NumPy:")
numpy_result = np.dot(w.T, X)
print(f"np.dot(w.T, X) = {numpy_result}")

Manual calculation of w.T x X:

Matrix shapes:
w.T shape: (1, 3)
X shape: (3, 4)
Result shape will be: (1, 4)

Number of examples to process: 4

Processing example 1:
  Feature 1: 0.2 × 1.0 = 0.2
  Feature 2: 0.3 × 0.5 = 0.15
  Feature 3: 0.1 × 2.0 = 0.2
  Final: 0.2 × 1.0 + 0.3 × 0.5 + 0.1 × 2.0 = 0.550

Processing example 2:
  Feature 1: 0.2 × 2.0 = 0.4
  Feature 2: 0.3 × 1.5 = 0.44999999999999996
  Feature 3: 0.1 × 1.0 = 0.1
  Final: 0.2 × 2.0 + 0.3 × 1.5 + 0.1 × 1.0 = 0.950

Processing example 3:
  Feature 1: 0.2 × 3.0 = 0.6000000000000001
  Feature 2: 0.3 × 2.5 = 0.75
  Feature 3: 0.1 × 3.0 = 0.30000000000000004
  Final: 0.2 × 3.0 + 0.3 × 2.5 + 0.1 × 3.0 = 1.650

Processing example 4:
  Feature 1: 0.2 × 4.0 = 0.8
  Feature 2: 0.3 × 3.5 = 1.05
  Feature 3: 0.1 × 2.5 = 0.25
  Final: 0.2 × 4.0 + 0.3 × 3.5 + 0.1 × 2.5 = 2.100

Verification with NumPy:
np.dot(w.T, X) = [[0.55 0.95 1.65 2.1 ]]


### Step-by-Step Vectorization example

In [13]:
import numpy as np

m = 4   # 4 training examples
nx = 3  # 3 features per example

# Input matrix X (3 features x $ examples)
X = np.array(
    [
        [1.0, 2.0, 3.0, 4.0],   # Feature 1 for all examples
        [0.5, 1.5, 2.5, 3.5],   # Feature 2 for all examples
        [2.0, 1.0, 3.0, 2.5],   # Feature 3 for all examples
    ]
)

# Weights (3 features x 1)
w = np.array(
    [
        [0.2],  # Weight for feature 1
        [0.3],  # Weight for feature 2
        [0.1]   # Weight for feature 3
    ]
)

# Bias
b = 0.5

print("X shape:", X.shape)  # (3, 4)
print("w shape:", w.shape)  # (3, 1)
print("X:\n", X)
print("w:\n", w)

X shape: (3, 4)
w shape: (3, 1)
X:
 [[1.  2.  3.  4. ]
 [0.5 1.5 2.5 3.5]
 [2.  1.  3.  2.5]]
w:
 [[0.2]
 [0.3]
 [0.1]]


#### Method 1: Loop Approach (Slow)

In [14]:
import time

def sigmoid(z):
    return 1/ (1 + np.exp(-z))

# SLOW: Loop through each example one by one
start_time = time.time()
predictions_loop = []

# For each training example
for i in range(m):
    # Extract one example (column i)
    x_i = X[:,i]    # Shape: (3,1) - one column
    print(f"Example {i+1}: x = {x_i}")

    # Compute linear combination: w.T . x_i + b
    z_i = np.dot(w.T, x_i) + b  #scalar result
    print(f"  z_{i+1} = w.T · x_{i+1} + b = {z_i[0]:.3f}")

    # Apply activation function
    pred_i = sigmoid(z_i)
    predictions_loop.append(pred_i[0])
    print(f"  prediction_{i+1} = sigmoid(z_{i+1}) = {pred_i[0]:.3f}")
    print()

loop_time = time.time() - start_time
print(f"Loop approach took: {loop_time:.6f} seconds")
print(f"Final predictions: {predictions_loop}")

Example 1: x = [1.  0.5 2. ]
  z_1 = w.T · x_1 + b = 1.050
  prediction_1 = sigmoid(z_1) = 0.741

Example 2: x = [2.  1.5 1. ]
  z_2 = w.T · x_2 + b = 1.450
  prediction_2 = sigmoid(z_2) = 0.810

Example 3: x = [3.  2.5 3. ]
  z_3 = w.T · x_3 + b = 2.150
  prediction_3 = sigmoid(z_3) = 0.896

Example 4: x = [4.  3.5 2.5]
  z_4 = w.T · x_4 + b = 2.600
  prediction_4 = sigmoid(z_4) = 0.931

Loop approach took: 0.003209 seconds
Final predictions: [np.float64(0.740774899182154), np.float64(0.8099984339846871), np.float64(0.8956687768809987), np.float64(0.9308615796566533)]


#### Method 2: Vectorized Approach (Fast)

In [15]:
# Fast: Process all examples simultaneously
start_time = time.time()

# Single matrix operation handles all examples at once
Z = np.dot(w.T, X) + b  # Shape: (1,4)
print("Z (all linear combinations):", Z)

# Apply sigmoid to ALL results simultaneously
predictions_vectorized = sigmoid(Z)
print("Predictions (vectorized):", predictions_vectorized[0])

vectorized_time = time.time() - start_time
print(f"Vectorized approach took: {vectorized_time:.6f} seconds")

# Verify both methods give same result
print(f"Results match: {np.allclose(predictions_loop, predictions_vectorized[0])}")

Z (all linear combinations): [[1.05 1.45 2.15 2.6 ]]
Predictions (vectorized): [0.7407749  0.80999843 0.89566878 0.93086158]
Vectorized approach took: 0.001470 seconds
Results match: True


#### Matrix Operation Breakdown

In [16]:
# Manual matrix multiplication to show what np.dot(w.T, X) does
print("Manual calculation of w.T . X:")
print("w.T shape:", w.T.shape)  # (1, 3)
print("X shape:", X.shape)      # (3, 4)
print("Result shape:", (w.T.shape[0], X.shape[1]))  # (1, 4)

# w.T = [[0.2, 0.3, 0.1]]

# X = [[1.0, 2.0, 3.0, 4.0],
#      [0.5, 1.5, 2.5, 3.5],
#      [2.0, 1.0, 3.0, 2.5]]

print("\nCalculating each element:")
# For each example
for j in range(X.shape[1]):
    result = 0
    calculation = ""

    # For each feature
    for i in range(w.shape[0]):
        contrib = w[i,0] * X[i,j]
        result += contrib
        calculation += f"{w[i,0]}×{X[i,j]}"
        if i < w.shape[0]-1:
            calculation += " + "

    print(f"Example {j+1}: {calculation} = {result:.3f}")


# This is exactly what np.dot(w.T, X) computes in one optimized operation!

Manual calculation of w.T . X:
w.T shape: (1, 3)
X shape: (3, 4)
Result shape: (1, 4)

Calculating each element:
Example 1: 0.2×1.0 + 0.3×0.5 + 0.1×2.0 = 0.550
Example 2: 0.2×2.0 + 0.3×1.5 + 0.1×1.0 = 0.950
Example 3: 0.2×3.0 + 0.3×2.5 + 0.1×3.0 = 1.650
Example 4: 0.2×4.0 + 0.3×3.5 + 0.1×2.5 = 2.100


### Real world performance comparison

In [17]:
# Scale up to see dramatic performance difference
m_large = 100000  # 100k examples
nx_large = 784    # 28×28 image pixels

# Create large random dataset
X_large = np.random.randn(nx_large, m_large)
w_large = np.random.randn(nx_large, 1)
b_large = 0.5

print(f"Dataset size: {nx_large} features × {m_large} examples")

# Time the loop approach (we'll only do a subset to avoid waiting)
m_subset = 1000
start_time = time.time()
predictions_loop_large = []
for i in range(m_subset):
    z_i = np.dot(w_large.T, X_large[:, i]) + b_large
    predictions_loop_large.append(sigmoid(z_i)[0])
loop_time_large = time.time() - start_time

# Extrapolate to full dataset
estimated_full_loop_time = loop_time_large * (m_large / m_subset)

# Time the vectorized approach (full dataset)
start_time = time.time()
Z_large = np.dot(w_large.T, X_large) + b_large
predictions_vectorized_large = sigmoid(Z_large)
vectorized_time_large = time.time() - start_time

print(f"\nPerformance Results:")
print(f"Loop approach (estimated): {estimated_full_loop_time:.3f} seconds")
print(f"Vectorized approach: {vectorized_time_large:.3f} seconds")
print(f"Speedup: {estimated_full_loop_time/vectorized_time_large:.1f}x faster")

Dataset size: 784 features × 100000 examples

Performance Results:
Loop approach (estimated): 0.351 seconds
Vectorized approach: 0.041 seconds
Speedup: 8.6x faster


## Practical Implementation with NumPy

### Essential NumPy Functions for Neural Networks

#### 1.Array Creation and Manipulation

In [18]:
import numpy as np

# create arrays - 2x3 matrix
X = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

print("X shape:", X.shape)
print("X:\n", X)


X shape: (2, 3)
X:
 [[1 2 3]
 [4 5 6]]


In [20]:
# Reshape arrays
X_flat = X.reshape(-1,1)    # FLatten to column vector
print("X_flat shape:", X_flat.shape)  # Output: (6, 1)
print("X_flat :\n",X_flat)

X_flat shape: (6, 1)
X_flat :
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


#### 2.Matrix Operations

In [22]:
# matrix multiplication - (2x2) and (2x2)
A = np.array(
    [
        [1, 2], 
        [3, 4]
    ]
)  # 2x2
B = np.array(
    [
        [5, 6], 
        [7, 8]
    ]
)  # 2x2

# Element-wise multiplication
elementwise = A * B
print("Element-wise A * B:\n", elementwise)

# Matrix multiplication
matrix_mult = np.dot(A, B)
print("Matrix multiplication A·B:\n", matrix_mult)

Element-wise A * B:
 [[ 5 12]
 [21 32]]
Matrix multiplication A·B:
 [[19 22]
 [43 50]]


#### 3.Vectorized Functions

In [23]:
# Apply functions to entire arrays at once
z = np.array([-2, -1, 0, 1, 2])

# Sigmoid function (vectorized)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

sigmoid_z = sigmoid(z)
print("z:",z)
print("sigmoid(z):",sigmoid_z)

z: [-2 -1  0  1  2]
sigmoid(z): [0.11920292 0.26894142 0.5        0.73105858 0.88079708]


### Broadcasting

#### Example 1: Adding a scalar to a matrix

In [24]:
# Shape: (2, 3)
X = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

# Scalar
b = 10

# Broadcasting: scalar added to each element
result = X + b
print("X + b:\n", result)

X + b:
 [[11 12 13]
 [14 15 16]]


### Example 2: Adding arrays with different shapes

In [25]:
# Neural network example: adding bias to multiple examples
# Weights: (3,1)
W = np.array([
    [0.1],
    [0.2],
    [0.3]
])

# Features: (3, 3)
X = np.array([
    [1, 2, 4],
    [3, 1, 2],
    [2, 4, 1]]
)

# Bias: (3, 1)
b = np.array([
    [0.5],
    [0.3],
    [0.1]]
)

# Linear transformation: Z = W·X + b
Z = np.dot(W.T, X) + b.T  # Broadcasting happens here
print("Z shape:", Z.shape)  # Output: (1, 3)
print("Z:", Z)

Z shape: (1, 3)
Z: [[1.8 1.9 1.2]]


### Key NumPy Functions for Neural Networks

In [27]:
import numpy as np

print("=" * 60)
print("KEY NUMPY FUNCTIONS FOR NEURAL NETWORKS")
print("=" * 60)

# =============================================================================
# 1. MATHEMATICAL FUNCTIONS
# =============================================================================
print("\n1. Mathematical Functions")
print("-" * 30)

# Sample data for demonstrations
x = np.array([-2, -1, 0, 1, 2])
print(f"Sample input: x = {x}")
print()

# Exponential function
exp_result = np.exp(x)
print(f"np.exp(x) = {exp_result}")
print("  Usage: Sigmoid activation, softmax")
print()

# Natural logarithm
x_positive = np.array([0.1, 1, 2.718, 10])
log_result = np.log(x_positive)
print(f"np.log({x_positive}) = {log_result}")
print("  Usage: Cross-entropy loss, log-likelihood")
print()

# ReLU activation function
relu_result = np.maximum(0, x)
print(f"np.maximum(0, x) = {relu_result}")
print("  Usage: ReLU activation (most common)")
print()

# Sum along axis
matrix_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
sum_axis1 = np.sum(matrix_2d, axis=1, keepdims=True)
print(f"Sample matrix:\n{matrix_2d}")
print(f"np.sum(matrix, axis=1, keepdims=True) =\n{sum_axis1}")
print("  Usage: Computing costs, normalization")

KEY NUMPY FUNCTIONS FOR NEURAL NETWORKS

1. Mathematical Functions
------------------------------
Sample input: x = [-2 -1  0  1  2]

np.exp(x) = [0.13533528 0.36787944 1.         2.71828183 7.3890561 ]
  Usage: Sigmoid activation, softmax

np.log([ 0.1    1.     2.718 10.   ]) = [-2.30258509  0.          0.99989632  2.30258509]
  Usage: Cross-entropy loss, log-likelihood

np.maximum(0, x) = [0 0 0 1 2]
  Usage: ReLU activation (most common)

Sample matrix:
[[1 2 3]
 [4 5 6]]
np.sum(matrix, axis=1, keepdims=True) =
[[ 6]
 [15]]
  Usage: Computing costs, normalization


In [28]:
# =============================================================================
# 2. ARRAY OPERATIONS
# =============================================================================
print("\n2. Array Operations")
print("-" * 25)

# Matrix multiplication
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

dot_result = np.dot(A, B)
print(f"Matrix A:\n{A}")
print(f"Matrix B:\n{B}")
print(f"np.dot(A, B) =\n{dot_result}")
print("  Usage: Forward/backward propagation")
print()

# Reshape
original = np.array([[1, 2, 3, 4]])
reshaped = np.reshape(original, (4, 1))
print(f"Original shape {original.shape}: {original}")
print(f"Reshaped to {reshaped.shape}:\n{reshaped}")
print("  Usage: Converting images to vectors")
print()

# Transpose
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
transposed = np.transpose(matrix)  # or matrix.T
print(f"Original matrix:\n{matrix}")
print(f"Transposed:\n{transposed}")
print("  Usage: Weight matrices, gradient computation")


2. Array Operations
-------------------------
Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
np.dot(A, B) =
[[19 22]
 [43 50]]
  Usage: Forward/backward propagation

Original shape (1, 4): [[1 2 3 4]]
Reshaped to (4, 1):
[[1]
 [2]
 [3]
 [4]]
  Usage: Converting images to vectors

Original matrix:
[[1 2 3]
 [4 5 6]]
Transposed:
[[1 4]
 [2 5]
 [3 6]]
  Usage: Weight matrices, gradient computation


In [29]:
# =============================================================================
# 3. RANDOM NUMBER GENERATION & INITIALIZATION
# =============================================================================
print("\n3. Random Number Generation & Initialization")
print("-" * 45)

# Set seed for reproducible results
np.random.seed(42)

# Random normal distribution
randn_result = np.random.randn(2, 3)
print(f"np.random.randn(2, 3) =\n{randn_result}")
print("  Usage: Weight initialization")
print()

# Random uniform [0,1]
rand_result = np.random.rand(2, 3)
print(f"np.random.rand(2, 3) =\n{rand_result}")
print("  Usage: Dropout, data augmentation")
print()

# Array of zeros
zeros_result = np.zeros((2, 3))
print(f"np.zeros((2, 3)) =\n{zeros_result}")
print("  Usage: Bias initialization, gradient accumulation")
print()

# Array of ones
ones_result = np.ones((2, 3))
print(f"np.ones((2, 3)) =\n{ones_result}")
print("  Usage: Masks, batch normalization")


3. Random Number Generation & Initialization
---------------------------------------------
np.random.randn(2, 3) =
[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]]
  Usage: Weight initialization

np.random.rand(2, 3) =
[[0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]]
  Usage: Dropout, data augmentation

np.zeros((2, 3)) =
[[0. 0. 0.]
 [0. 0. 0.]]
  Usage: Bias initialization, gradient accumulation

np.ones((2, 3)) =
[[1. 1. 1.]
 [1. 1. 1.]]
  Usage: Masks, batch normalization


In [30]:
# =============================================================================
# 4. NEURAL NETWORK EXAMPLE: Putting it all together
# =============================================================================
print("\n4. Mini Neural Network Example")
print("-" * 35)

# Initialize weights and bias
np.random.seed(1)
W = np.random.randn(3, 2) * 0.01  # Small random weights
b = np.zeros((3, 1))              # Zero bias
X = np.random.randn(2, 4)         # 4 training examples, 2 features

print(f"Weights W shape: {W.shape}")
print(f"Bias b shape: {b.shape}")
print(f"Input X shape: {X.shape}")
print()

# Forward propagation step
Z = np.dot(W, X) + b              # Linear transformation
A = np.maximum(0, Z)              # ReLU activation

print(f"Linear output Z = W·X + b, shape: {Z.shape}")
print(f"After ReLU activation A, shape: {A.shape}")
print(f"Sample activation values:\n{A}")

print("\n" + "=" * 60)
print("All functions demonstrated with runnable examples!")
print("=" * 60)


4. Mini Neural Network Example
-----------------------------------
Weights W shape: (3, 2)
Bias b shape: (3, 1)
Input X shape: (2, 4)

Linear output Z = W·X + b, shape: (3, 4)
After ReLU activation A, shape: (3, 4)
Sample activation values:
[[0.01939723 0.00023841 0.0071547  0.        ]
 [0.         0.02612514 0.00177436 0.00543789]
 [0.         0.04082739 0.01018155 0.00668109]]

All functions demonstrated with runnable examples!
